### PR TITLE
Added some build dependencies for debian

### LINKED ISSUE #408: Installation error on kali linux
Os details:
--------------
PRETTY_NAME="Kali GNU/Linux Rolling"
NAME="Kali GNU/Linux"
ID=kali
VERSION="2020.4"
VERSION_ID="2020.4"
VERSION_CODENAME="kali-rolling"
ID_LIKE=debian

While running "make deb", the following error occurs
~~~
fakeroot debian/rules binary
dh binary --with systemd
   dh_testroot
   dh_prep
   dh_installdirs
/media/vivek/4B6AE0131AB3ED1E1/FOSS/Libreswan/debian/libreswan.dirs: 1: /var/lib/ipsec/nss: not found
dh_installdirs: warning: debian/libreswan.dirs is marked executable but does not appear to an executable config.
dh_installdirs: warning: 
dh_installdirs: warning: If debian/libreswan.dirs is intended to be an executable config file, please ensure it can
dh_installdirs: warning: be run as a stand-alone script/program (e.g. "./debian/libreswan.dirs")
dh_installdirs: warning: Otherwise, please remove the executable bit from the file (e.g. chmod -x "debian/libreswan.dirs")
dh_installdirs: warning: 
dh_installdirs: warning: Please see "Executable debhelper config files" in debhelper(7) for more information.
dh_installdirs: warning: 
dh_installdirs: error: debian/libreswan.dirs (executable config) returned exit code 127
make: *** [debian/rules:6: binary] Error 25
dpkg-buildpackage: error: fakeroot debian/rules binary subprocess returned exit status 2
debuild: fatal error at line 1182:
dpkg-buildpackage -us -uc -ui -i -b failed
make[1]: *** [Makefile:7: deb] Error 29
make[1]: Leaving directory '/media/vivek/4B6AE0131AB3ED1E1/FOSS/Libreswan/packaging/debian'
make: *** [Makefile:184: deb] Error 2
~~~

### PR DESCRIPTION
**Pull request by vivekvardhanadepu**
Fixes #408 
Added some build dependencies, which were not present on my system(kali-rolling). So, maybe other debian distros as well

### CODE REVIEW

**Comment by dkg** [comment]
Thanks for this suggestion, @vivekvardhanadepu !  it looks like some of these suggestions are just copying requirements found in the list of build-dependencies for `packaging/debian/control`.

It seems like this list might depend at least in part on which version of debian/ubuntu the user is using.  For example, `dh_systemd` in debian testing today (bullseye) is a dummy/transitional package, and it is *not* recommended to encourage people to install it.  It hasn't been used in the packaging used [for libreswan in debian itself](https://tracker.debian.org/pkg/libreswan) since the packaging [migrated to debhelper 11 several years ago](https://salsa.debian.org/debian/libreswan/-/commit/b0404596b9299b82d480787049b807251db729bf).  I recommend dropping the recommendation for dh-systemd (and the `--with systemd` bits in `packaging/debian/rules` for that matter).

While you're editing this section, maybe you also want to remove the suggestion to `USE_DNSSEC=false`, since that should *not* be necessary on any modern debian system.

**Comment by dkg** [comment]
i guess dropping `dh-systemd` (which i recommend) would require moving to a more modern version of debhelper (version 11 or later).

I'm not sure why the upstream proposed debian packaging (the stuff in `packaging/debian/`) insists on debhelper version 9, which is quite old.  Even debian oldstable ("stretch") has debhelper 10.2.5, and anyone building on a system that old might have other problems; stretch-backports has debhelper 12.1.1, so if the goal is backporting to stretch, you can just rely on the more modern dh in backports.

debian upstream packaging is using dh 13, fwiw.

Maybe the libreswan devs (i'm just a debian packager) can tell us whether they are ok with moving to a more modern dh for the debian packaging that they ship.  @letoams or @oerdnj might be the relevant folks to answer this question.

**Comment by letoams** [comment]
On Tue, 2 Feb 2021, dkg wrote:

> i guess dropping dh-systemd (which i recommend) would require moving to a more modern version of debhelper
> (version 11 or later).
> 
> I'm not sure why the upstream proposed debian packaging (the stuff in packaging/debian/) insists on
> debhelper version 9

I'm sure it is only due to bit rot.

If you have a patch for me to update the packaging/debian/ files, I'll
pull them in. Or if it is just updating the version number and removing
dh-systemd, then I can make the change too.

> Maybe the libreswan devs (i'm just a debian packager) can tell us whether they are ok with moving to a
> more modern dh for the debian packaging that they ship. @letoams or @oerdnj might be the relevant folks to
> answer this question.

I'd be happy for the packaging/debian to be updated. We provide it to
help the users who run our code on debian/ubuntu, and who are not
package maintainers themselves, but need a newer libreswan than their
debian / ubuntu flavour carries. We want to support them to just type
a simple command (make deb) to get their packages.

Paul

**Comment by dkg** [comment]
On Tue 2021-02-02 15:07:03 -0800, Paul Wouters wrote:
> I'd be happy for the packaging/debian to be updated. We provide it to
> help the users who run our code on debian/ubuntu, and who are not
> package maintainers themselves, but need a newer libreswan than their
> debian / ubuntu flavour carries. We want to support them to just type
> a simple command (make deb) to get their packages.

Makes sense, and this is maybe also a reason to not just directly copy
the packaging that we use for debian unstable, which might take
advantage of more up-to-date packaging tools -- you want a "lowest
common denominator" set of build dependencies.

The question is how far back do you want to go?  if we update it to use
dh 11, that'll rule out people building with "make deb" on Ubuntu xenial
or earlier, for example.

The traditional debian answer here, of course, is "use the backports
repositories" -- then people don't have to even install build-deps or
run "make", they can just "apt install libreswan/buster-backports" or
whatever.

If debian backports is something you're interested in, please let me
know.  I can try to do that kind of backport work for debian.  I don't
know how to do it in ubuntu, though.

**Comment by vivekvardhanadepu** [comment]
> Thanks for this suggestion, @vivekvardhanadepu ! it looks like some of these suggestions are just copying requirements found in the list of build-dependencies for `packaging/debian/control`.
> 
> It seems like this list might depend at least in part on which version of debian/ubuntu the user is using. For example, `dh_systemd` in debian testing today (bullseye) is a dummy/transitional package, and it is _not_ recommended to encourage people to install it. It hasn't been used in the packaging used [for libreswan in debian itself](https://tracker.debian.org/pkg/libreswan) since the packaging [migrated to debhelper 11 several years ago](https://salsa.debian.org/debian/libreswan/-/commit/b0404596b9299b82d480787049b807251db729bf). I recommend dropping the recommendation for dh-systemd (and the `--with systemd` bits in `packaging/debian/rules` for that matter).
> 
> While you're editing this section, maybe you also want to remove the suggestion to `USE_DNSSEC=false`, since that should _not_ be necessary on any modern debian system.

I have removed `dh_systemd` from control and also dropped `--with systemd`. It has been built successfully :grinning: :grinning:
Thanks!!

**Comment by dkg** [comment]
I recommend closing this pull request, as it does not seem necessary any longer (debian buster is now oldstable)

**Comment by vivekvardhanadepu** [comment]
Sure!!

**Pull request closed without merging**
