### PR TITLE
Clang build fixes

### PR DESCRIPTION
**Pull request by tbaederr**
See individual commits

### CODE REVIEW

**Review by cagney — CHANGES_REQUESTED** [review]
- header lswcdefs.h defines the macro:
`# define PRINTF_LIKE(n) __attribute__ ((format(printf, n, n + 1)))`
can an equivalent VPRINTF_LIKE() macro be defined?
- would it be better to attach this to the declaration - that way the compiler can also check callers?

**Comment by tbaederr** [comment]
At least `alloc_vprintf` already has a `PRINTF_LIKE` attribute in the declaration, but I guess that's not being used when compiled with clang because `GCC_LINT` is not set.

**Review by cagney — COMMENTED** [review]
The idiom exists for a reason.
clang made their error non-specific: https://reviews.llvm.org/D55382
gcc doesn't support this:
https://gcc.gnu.org/pipermail/gcc-patches/2017-February/469872.html
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=62181

**Comment by cagney** [comment]
> At least `alloc_vprintf` already has a `PRINTF_LIKE` attribute in the declaration, but I guess that's not being used when compiled with clang because `GCC_LINT` is not set.

 `mk/config.mk` has:
```
ifeq ($(origin GCC_LINT),undefined)
GCC_LINT = -DGCC_LINT
endif
USERLAND_CFLAGS += $(GCC_LINT)
```
so GCC_LINT should be defined?

Can I also suggest splitting these two patches, they are for different problems.

**Comment by tbaederr** [comment]
> The idiom exists for a reason.
> clang made their error non-specific: https://reviews.llvm.org/D55382
> gcc doesn't support this:
> https://gcc.gnu.org/pipermail/gcc-patches/2017-February/469872.html
> https://gcc.gnu.org/bugzilla/show_bug.cgi?id=62181

I know, I'm not a fan of the warning either. But if libreswan should be buildable with clang and you don't want to have clang-specific cflags somewhere, this is how to fix it I guess.

**Comment by tbaederr** [comment]
> > At least `alloc_vprintf` already has a `PRINTF_LIKE` attribute in the declaration, but I guess that's not being used when compiled with clang because `GCC_LINT` is not set.
> 
> `mk/config.mk` has:
> 
> ```
> ifeq ($(origin GCC_LINT),undefined)
> GCC_LINT = -DGCC_LINT
> endif
> USERLAND_CFLAGS += $(GCC_LINT)
> ```
> 
> so GCC_LINT should be defined?
> 
> Can I also suggest splitting these two patches, they are for different problems.

I'll have to investigate. Split them how into what? Two PRs?

**Comment by cagney** [comment]
> > The idiom exists for a reason.
> > clang made their error non-specific: https://reviews.llvm.org/D55382
> > gcc doesn't support this:
> > https://gcc.gnu.org/pipermail/gcc-patches/2017-February/469872.html
> > https://gcc.gnu.org/bugzilla/show_bug.cgi?id=62181
> 
> I know, I'm not a fan of the warning either. But if libreswan should be buildable with clang and you don't want to have clang-specific cflags somewhere, this is how to fix it I guess.

Yes.  Might have to just suck it up.
I've pointed DHR at this on IRC.

**Comment by cagney** [comment]
> > > At least `alloc_vprintf` already has a `PRINTF_LIKE` attribute in the declaration, but I guess that's not being used when compiled with clang because `GCC_LINT` is not set.
> > 
> > 
> > `mk/config.mk` has:
> > ```
> > ifeq ($(origin GCC_LINT),undefined)
> > GCC_LINT = -DGCC_LINT
> > endif
> > USERLAND_CFLAGS += $(GCC_LINT)
> > ```
> > 
> > 
> > so GCC_LINT should be defined?
> > Can I also suggest splitting these two patches, they are for different problems.
> 
> I'll have to investigate. Split them how into what? Two PRs?

Branch?  New pull request?  (I really don't know how to drive github)

For GCC_LINT, let us know, it might be easier to drop the #ifdef GCC_LINT wrapper

**Comment by tbaederr** [comment]
There are a bunch of other problems, but I'll create separate pull requests for all of them, starting with https://github.com/libreswan/libreswan/pull/393. Thanks.

**Pull request closed without merging**
