### PR TITLE
xfrm refcount ips

### PR DESCRIPTION
**Pull request by bradyallenjohnson**

### CODE REVIEW

**Comment by antonyantony** [comment]
thanks for the PR. I gave it a try. first time I got an error. Then I tried 
to re-run it manually in namespace and that run hit Segmentation fault.

I added config line. Is that correct?
leftinterface-ip=192.0.1.251/24

 ipsec auto --up west
1v2 "west" #1: initiating IKEv2 connection
1v2 "west" #1: sent IKE_SA_INIT request to 192.1.2.23:500
1v2 "west" #1: sent IKE_AUTH request {cipher=AES_GCM_16_256 integ=n/a prf=HMAC_SHA2_512 group=MODP2048}
003 "west" #1: initiator established IKE SA; authenticated peer using authby=secret and ID_FQDN ***@***.***'
003 ERROR: "west" #2: No IP to set on xfrmi device [ipsec1] id [1]
003 "west" #2: CHILD SA encountered fatal error: INVALID_SYNTAX
036 "west" #1: encountered fatal error in state STATE_V2_ESTABLISHED_IKE_SA
002 "west" #2: deleting larval Child SA (DELETE_IKE)
003 ERROR: "west" #2: netlink response for Del SA ***@***.***: No such process (errno 3)
002 "west" #1: connection is supposed to remain up; revival attempt 1 scheduled in 0 seconds
002 "west" #1: deleting IKE SA (ESTABLISHED_IKE_SA) and NOT sending notification
west #

The above output from kvm runner. And when tried to restart namespace  seg 
fault.

gdb bt from namesapce re-run.

"Program terminated with signal SIGSEGV, Segmentation fault."

I will push a testcase that I used. ikev2-xfrmi-15-interface-ip

Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000055a06442ad81 in refcnt_addref_where (what=0x55a06446f09b "xfrmi_ipaddr", pointer=0x55a06592f5a8,
    refcnt=0x55a06592f5f0, where=0x55a0644e7760 <here>) at /home/build/libreswan/lib/libswan/refcnt.c:93
93		DEBUG_LOG("add");

(gdb) bt
#0  0x000055a06442ad81 in refcnt_addref_where (what=0x55a06446f09b "xfrmi_ipaddr", pointer=0x55a06592f5a8,
    refcnt=0x55a06592f5f0, where=0x55a0644e7760 <here>) at /home/build/libreswan/lib/libswan/refcnt.c:93
#1  0x000055a06432cb10 in reference_xfrmi_ip (xfrmi=0x55a065923eb8, xfrmi_ipaddr=0x55a06592f5a8)
    at /home/build/libreswan/programs/pluto/kernel_xfrm_interface.c:441
#2  0x000055a06432ecba in add_xfrm_interface (c=0x55a06591f868, logger=0x55a06592c438)
    at /home/build/libreswan/programs/pluto/kernel_xfrm_interface.c:1138
#3  0x000055a0643d30f6 in process_v2_child_response_payloads (ike=0x55a065924808, child=0x55a06592c958,
    md=0x55a065925968) at /home/build/libreswan/programs/pluto/ikev2_child.c:813
#4  0x000055a0643d3dce in process_v2_IKE_AUTH_response_child_sa_payloads (ike=0x55a065924808,
    response_md=0x55a065925968) at /home/build/libreswan/programs/pluto/ikev2_child.c:1160
#5  0x000055a0642e122d in process_v2_IKE_AUTH_response_post_cert_decode (ike_sa=0x55a065924808, md=0x55a065925968)
    at /home/build/libreswan/programs/pluto/ikev2_ike_auth.c:1441
#6  0x000055a0642e09c3 in process_v2_IKE_AUTH_response (ike=0x55a065924808, unused_child=0x0, md=0x55a065925968)
    at /home/build/libreswan/programs/pluto/ikev2_ike_auth.c:1290
#7  0x000055a0643cc7ee in v2_dispatch (ike=0x55a065924808, md=0x55a065925968,
    svm=0x55a064510e60 <v2_state_transition_table+672>) at /home/build/libreswan/programs/pluto/ikev2.c:2330
#8  0x000055a0643cc6ad in process_protected_v2_message (ike=0x55a065924808, md=0x55a065925968)
    at /home/build/libreswan/programs/pluto/ikev2.c:2297
#9  0x000055a0643cc3ae in process_packet_with_secured_ike_sa (md=0x55a065925968, ike=0x55a065924808)
    at /home/build/libreswan/programs/pluto/ikev2.c:2212
#10 0x000055a0643cb5a9 in ikev2_process_packet (md=0x55a065925968)
    at /home/build/libreswan/programs/pluto/ikev2.c:1901
#11 0x000055a0643e3165 in process_md (md=0x55a065925968) at /home/build/libreswan/programs/pluto/demux.c:189
#12 0x000055a0643e3442 in process_iface_packet (fd=17, ifp_arg=0x0, logger=0x7ffc73df13b0)
    at /home/build/libreswan/programs/pluto/demux.c:296
#13 0x000055a06438c1cd in fd_read_listener_event_handler (fd=17, events=2, arg=0x55a06591f718)
    at /home/build/libreswan/programs/pluto/server.c:793
#14 0x00007fcc52f92ca5 in event_process_active_single_queue () from /lib64/libevent_core-2.1.so.7
#15 0x00007fcc52f9480f in event_base_loop () from /lib64/libevent_core-2.1.so.7
#16 0x000055a06438d31f in run_server (conffile=0x55a06584fc38 "/etc/ipsec.conf", logger=0x7ffc73df1710)
    at /home/build/libreswan/programs/pluto/server.c:1068
#17 0x000055a064386a64 in main (argc=4, argv=0x7ffc73df1cd8)
    at /home/build/libreswan/programs/pluto/plutomain.c:1824

**Comment by bradyallenjohnson** [comment]
@antonyantony Thanks for trying this, I havent gotten that far yet. I first tried with the simplest test `basic-pluto-01` and get a failure: https://pastebin.com/6QjzjSaj I also get that failure on the git main branch, so Im not sure what is happening.

I believe the syntax should be `interface-ip=` without the left/right prefix. I'll try testing manually now too.

**Comment by cagney** [comment]
```
$ ./kvm failed
testing/pluto/ikev2-xfrmi-06 failed east:output-different road:iscntrl,output-different
testing/pluto/ikev2-xfrmi-08 failed west:LEAK,PRINTF_NULL,output-different
testing/pluto/ikev2-xfrmi-10 failed west:LEAK,PRINTF_NULL,output-different
testing/pluto/ikev1-xfrmi-05-remote-access-client failed east:output-different road:output-different
```

**Comment by cagney** [comment]
```
--- MASTER/testing/pluto/ikev2-xfrmi-06/road.console.txt
+++ OUTPUT/testing/pluto/ikev2-xfrmi-06/road.console.txt
@@ -22,6 +22,7 @@
 002 "road"[1] 192.1.2.23 #2: received INTERNAL_IP4_DNS 1.2.3.4
 002 "road"[1] 192.1.2.23 #2: received INTERNAL_IP4_DNS 8.8.8.8
 002 "road"[1] 192.1.2.23 #2: up-client output: updating resolvconf
+002 "road"[1] 192.1.2.23 #2: route-client output: PATH/libexec/ipsec/_updown.xfrm: doroute "ip -4 route replace 0.0.0.0/1   dev ipsec1 src 192.0.2.1 && 		ip -4 route replace 128.0.0.0/1   dev ipsec1 src 192.0.2.1" failed (Error: Invalid prefsrc address.)
 004 "road"[1] 192.1.2.23 #2: initiator established Child SA using #1; IPsec tunnel [192.0.2.1-192.0.2.1:0-65535 0] -> [0.0.0.0-255.255.255.255:0-65535 0] {ESP/ESN=>0xESPESP <0xESPESP xfrm=AES_GCM_16_256-NONE DPD=passive}
 road #
  ping -n -q -c 2 192.0.2.254
@@ -31,7 +32,7 @@
 rtt min/avg/max/mdev = 0.XXX/0.XXX/0.XXX/0.XXX ms
 road #
  ipsec whack --trafficstatus
-006 #2: "road"[1] 192.1.2.23, type=ESP, add_time=1234567890, inBytes=168, outBytes=168, maxBytes=2^63B, id='@east', lease=192.0.2.1/32
+006 #2: "road"[1] 192.1.2.23, type=ESP, add_time=1234567890, inBytes=0, outBytes=0, maxBytes=2^63B, id='@east', lease=192.0.2.1/32
```
from the log:
```
| cmd(   0):2>&1 PLUTO_VERB='route-client' PLUTO_CONNECTION='road' PLUTO_CONNECTION_TYPE='tu:
| cmd(  80):nnel' PLUTO_VIRT_INTERFACE='ipsec1' PLUTO_INTERFACE='eth0' PLUTO_XFRMI_ROUTE='ye:
| cmd( 160):s' PLUTO_NEXT_HOP='192.1.3.254' PLUTO_ME='192.1.3.209' PLUTO_MY_ID='@road' PLUTO:
| cmd( 240):_CLIENT_FAMILY='ipv4' PLUTO_MY_CLIENT='192.0.2.1/32' PLUTO_MY_CLIENT_NET='192.0.:
| cmd( 320):2.1' PLUTO_MY_CLIENT_MASK='255.255.255.255' PLUTO_MY_PORT=0 PLUTO_MY_PROTOCOL=0 :
| cmd( 400):PLUTO_SA_REQID=16393 PLUTO_SA_TYPE='ESP' PLUTO_PEER='192.1.2.23' PLUTO_PEER_ID=':
| cmd( 480):@east' PLUTO_PEER_CLIENT='0.0.0.0/0' PLUTO_PEER_CLIENT_NET='0.0.0.0' PLUTO_PEER_:
| cmd( 560):CLIENT_MASK='0.0.0.0' PLUTO_PEER_PORT=0 PLUTO_PEER_PROTOCOL=0 PLUTO_PEER_CA='' P:
| cmd( 640):LUTO_STACK='xfrm' PLUTO_ADDTIME=1691002967 PLUTO_CONN_POLICY='IKEv2+PSK+ENCRYPT+:
| cmd( 720):TUNNEL+PFS+UP+IKEV2_ALLOW_NARROWING+IKE_FRAG_ALLOW+ESN_NO+ESN_YES' PLUTO_CONN_KI:
| cmd( 800):ND='CK_INSTANCE' PLUTO_CONN_ADDRFAMILY='ipv4' XAUTH_FAILED=0 PLUTO_MY_SOURCEIP=':
| cmd( 880):192.0.2.1' PLUTO_MOBIKE_EVENT='' PLUTO_IS_PEER_CISCO=0 PLUTO_PEER_DNS_INFO='1.2.:
| cmd( 960):3.4 8.8.8.8' PLUTO_PEER_DOMAIN_INFO='' PLUTO_PEER_BANNER='' PLUTO_CFG_SERVER=0 P:
| cmd(1040):LUTO_CFG_CLIENT=1 PLUTO_NM_CONFIGURED=0 PLUTO_INBYTES=0 PLUTO_OUTBYTES=0 PLUTO_X:
| cmd(1120):FRMI_FWMARK='1/0xffffffff' VTI_IFACE='' VTI_ROUTING='no' VTI_SHARED='no' SPI_IN=:
| cmd(1200):0x95a8264 SPI_OUT=0x89c40f8a ipsec _updown:
"road"[1] 192.1.2.23 #2: route-client output: /usr/local/libexec/ipsec/_updown.xfrm: doroute "ip -4 route replace 0.0.0.0/1   dev ipsec1 src 192.0.2.1 &&               ip -4 route replace 128.0.0.0/1   dev ipsec1 src 192.0.2.1" failed (Error: Invalid prefsrc address.)
```

**Comment by cagney** [comment]
The leak is:
```
+:
+: checking reference leaks
+:
+ERROR: : '0x7f7be18d7f98' has count 1
+1193: Aug  2 15:03:36.818600: | newref struct pluto_xfrmi_ipaddr@0x7f7be18d7f98(0->1) (create_xfrmi_ipaddr() +388 programs/pluto/kernel_xfrm_interface.c)
+FAIL: reference leaks
```

**Comment by letoams** [comment]
On Wed, 2 Aug 2023, cagney wrote:

> +002 "road"[1] 192.1.2.23 #2: route-client output: PATH/libexec/ipsec/_updown.xfrm: doroute "ip -4 route replace 0.0.0.0/1   dev ips
> ec1 src 192.0.2.1 && 		ip -4 route replace 128.0.0.0/1   dev ipsec1 src 192.0.2.1" failed (Error: Invalid prefsrc address.)
>  004 "road"[1] 192.1.2.23 #2: initiator established Child SA using #1; IPsec tunnel [192.0.2.1-192.0.2.1:0-65535 0] -> [0.0.0.0-255.
> 255.255.255:0-65535 0] {ESP/ESN=>0xESPESP <0xESPESP xfrm=AES_GCM_16_256-NONE DPD=passive}

> "road"[1] 192.1.2.23 #2: route-client output: /usr/local/libexec/ipsec/_updown.xfrm: doroute "ip -4 route replace 0.0.0.0/1   dev ip
> sec1 src 192.0.2.1 &&               ip -4 route replace 128.0.0.0/1   dev ipsec1 src 192.0.2.1" failed (Error: Invalid prefsrc addre
> ss.)

Note that when we replace a route to 0/0, we use two "half routes", eg
0.0.0.0/1 and 128.0.0.0/1

Could it be that 192.0.2.1 was not put on the interface yet? So that it
had no better route than 128.0.0.0/1 for itself ?

**Comment by cagney** [comment]
> The memory leak was because the code was not deleting pluto_xfrmi_ipaddr that were created at init when there are already IPs on the interface that were not created by pluto.

that one is tricky; re-running tests

**Comment by cagney** [comment]
```
$ ./kvm failed
testing/pluto/ikev2-xfrmi-08 failed west:output-different
testing/pluto/ikev2-xfrmi-10 failed west:output-different
```
pfree() instead of delref()?
```
+:
+: checking memory leaks
+:
+PASS: memory leaks
+:
+: checking reference leaks
+:
+ERROR: : '0x7ff2e7a9df98' has count 1
+1193: Aug  5 07:57:33.796067: | newref struct pluto_xfrmi_ipaddr@0x7ff2e7a9df98(0->1) (create_xfrmi_ipaddr() +401 programs/pluto/kernel_xfrm_interface.c)
+FAIL: reference leaks
```

**Comment by bradyallenjohnson** [comment]
> ```
> $ ./kvm failed
> testing/pluto/ikev2-xfrmi-08 failed west:output-different
> testing/pluto/ikev2-xfrmi-10 failed west:output-different
> ```
> 
> pfree() instead of delref()?
> 
> ```
> +:
> +: checking memory leaks
> +:
> +PASS: memory leaks
> +:
> +: checking reference leaks
> +:
> +ERROR: : '0x7ff2e7a9df98' has count 1
> +1193: Aug  5 07:57:33.796067: | newref struct pluto_xfrmi_ipaddr@0x7ff2e7a9df98(0->1) (create_xfrmi_ipaddr() +401 programs/pluto/kernel_xfrm_interface.c)
> +FAIL: reference leaks
> ```

Thanks for pointing that out. Strange I didnt see that when I ran the tests yesterday. 

I was indeed calling pfree() without first calling delref(). Fixed and pushed.

**Comment by cagney** [comment]
> Strange I didnt see that when I ran the tests yesterday.

when run in batch mode kvm performs additional checks

the tests now pass; I'll do a full test run next; thanks

**Comment by cagney** [comment]
clean result:
```
$ ./kvm failed
Summary:
  stats/bad/ignored/status!=good: 1
  stats/freebsd/ignored/status!=good: 3
  stats/netbsd/ignored/status!=good: 26
  stats/openbsd/ignored/status!=good: 3
  stats/skiptest/ignored/status!=good: 13
  stats/wip/ignored/status!=good: 147
  tests/bad/results/untested: 1
  tests/freebsd/results/untested: 3
  tests/good/results/passed: 924
  tests/netbsd/results/untested: 26
  tests/openbsd/results/untested: 3
  tests/skiptest/results/untested: 13
  tests/wip/results/untested: 147
  total: 1117
  total/ignored: 193
  total/passed: 924
```
(had to re-run some unreliable tests, but that is unrelated)

**Comment by cagney** [comment]
For reference, I also ran the wip xfrmi tests using:
```
$ ./kvm check testing/pluto/*xfrmi*
```
this is how they compare:
```
$ ./testing/utils/kvmresults.py --test-status 'good|wip' --test-name xfrmi --print result,test-status,test-name .
passed good ikev2-xfrmi-01
passed good ikev2-xfrmi-02
passed wip ikev2-xfrmi-02-responder
passed good ikev2-xfrmi-03
passed good ikev2-xfrmi-04
failed wip ikev2-xfrmi-05-remote-access-client
passed good ikev2-xfrmi-06
passed good ikev2-xfrmi-07
passed good ikev2-xfrmi-08
passed good ikev2-xfrmi-09-systemd-networkd
passed good ikev2-xfrmi-10
passed good ikev2-xfrmi-11-default-manual-route
passed good ikev2-xfrmi-11-vti-default-route
passed good ikev2-xfrmi-11-default-route
passed good ikev2-xfrmi-12-two-default-routes
passed good ikev2-xfrmi-13-multiple-tunnels
unresolved wip ikev2-xfrmi-14-fwmark
passed good ikev1-xfrmi-01
failed wip ikev1-xfrmi-02
failed wip ikev1-xfrmi-02-tcpdump
failed wip ikev1-xfrmi-02-aggr
passed good ikev1-xfrmi-04
passed good ikev1-xfrmi-04-aggr
passed good ikev1-xfrmi-05-remote-access-client
unresolved wip ikev2-xfrmi-15-interface-ip
passed wip ikev2-xfrmi-16-rekey
passed good interop-ikev2-xfrmi-strongswan-01
```

**Review by cagney — APPROVED** [review]
Test results don't show any regressions.

**Review by paulwouters — APPROVED** [review]

**Comment by paulwouters** [comment]
merged!

**Pull request closed without merging**
