### PR TITLE
Introduce ppk-ids connection option as a prep work for draft-smyslov-ipsecme-ikev2-qr-alt-07 (PPKs during INTERMEDIATE exchange)

### PR DESCRIPTION
**Pull request by vukasink**
ppk-ids option allows for specifying a list of PPK_IDs to look for in .secrets file

I'm open to suggestions if something needs to be improved in the patch.

### CODE REVIEW

**Comment by vukasink** [comment]
Anyone had a change to take a look at this? :)

**Comment by cagney** [comment]
FYI, DBG_log() always debug-logs so ldbg(c->logger, ...) for many cases will be better

**Comment by cagney** [comment]
I see both get_connection_ppk_initiator() and ..._responder() slice and dice c->config->ppk_ids; should that instead be done once when adding the connection?

**Comment by vukasink** [comment]
Thanks, I'll update the code to use d605ba5648

**Comment by vukasink** [comment]
Updated the code to use d605ba5.

At some point I had to turn shunk_t into chunk_t by casting away the const qualifier.

An alternative would be to clone shunk_t into a new chunk_t, and then free the newly created chunk in the caller function, which seemed more complicated approach to me. But I do not have a strong opinion about it, so if anybody objects, let me know.

**Pull request merged**
