### PR TITLE
The XFRM address scope must be global

### PR DESCRIPTION
**Pull request by bradyallenjohnson**
- previously it was erroneously being set to 50

### CODE REVIEW

**Comment by cagney** [comment]
what did it break?

**Comment by cagney** [comment]
We discussed off list:

- the value `50` is simply wrong
- to demonstrate how `50` vs `0` breaks things requires libreswan being run in a container
Getting a container test working within the framework isn't something for 5.0, but should happen ref #1470
- fortunately we've tests that do show 50 instead of global; just need to confirm that they don't break

**Comment by cagney** [comment]
Do the kernel headers have a macro that should be used instead?

**Comment by cagney** [comment]
```
kvmrunner 1:42:04.06:   stats/freebsd/ignored/status!=good: 5
kvmrunner 1:42:04.06:   stats/netbsd/ignored/status!=good: 27
kvmrunner 1:42:04.06:   stats/openbsd/ignored/status!=good: 3
kvmrunner 1:42:04.06:   stats/skiptest/ignored/status!=good: 11
kvmrunner 1:42:04.06:   stats/wip/ignored/status!=good: 146
kvmrunner 1:42:04.06:   tests/freebsd/results/untested: 5
kvmrunner 1:42:04.06:   tests/good/results/passed: 986
kvmrunner 1:42:04.06:   tests/netbsd/results/untested: 27
kvmrunner 1:42:04.06:   tests/openbsd/results/untested: 3
kvmrunner 1:42:04.06:   tests/skiptest/results/untested: 11
kvmrunner 1:42:04.06:   tests/wip/results/untested: 146
kvmrunner 1:42:04.06:   total: 1178
kvmrunner 1:42:04.06:   total/ignored: 192
kvmrunner 1:42:04.06:   total/passed: 986
kvmrunner 1:42:04.06: run finished at 2023-12-14 12:58:04.070402 after 1:42:04.653129
```

```
commit 5cc6ba98eb209d46d7a75f72269952339331f628 (HEAD, bradyjoh/topic/xfrm_addr_scope)
Author: Brady Johnson <bradyjoh@redhat.com>
Date:   Thu Dec 14 09:56:31 2023 +0100

    The XFRM address scope must be global
    
    - previously it was erroneously being set to 50
    
    Signed-off-by: Brady Johnson <bradyallenjohnson@gmail.com>

```

**Comment by cagney** [comment]
```
 192.1.3.0/24 dev eth0 proto kernel scope link src 192.1.3.209
 road #
  ip route show table 50
-192.1.2.23 via 192.1.3.254 dev eth0
+Error: ipv4: FIB table does not exist.
+Dump terminated
 road #
```
need tweaking (I don't know)?

**Comment by bleve** [comment]
That is about route table 50. Not related.

**Comment by letoams** [comment]
Isn’t it related to? It’s the xfrm interface not setting scope to 50 anymore ?On Dec 14, 2023, at 15:17, Tuomo Soini ***@***.***> wrote:﻿
That is about route table 50. Not related.

**Comment by bleve** [comment]
ip route show table 50

Nothing to do with scope.

**Comment by cagney** [comment]
I suspect the kernel, when IPv6 ignores 50:
```
 X: ipsec1@eth0: <NOARP,UP,LOWER_UP> mtu 1500 state UNKNOWN
-    inet 192.0.2.1/32 scope 50 ipsec1
+    inet6 2001:db8:0:2::/32 scope global
+       valid_lft forever preferred_lft forever
+    inet6 fe80::b3aa:42c:c903:6a37/64 scope link stable-privacy proto kernel_ll
        valid_lft forever preferred_lft forever
```

**Comment by cagney** [comment]
This is a stab at an IPv6 test, output is for 5.0rc1:
https://github.com/cagney/libreswan/tree/testing/ikev2-xfrmi-06-ipv6/testing/pluto/ikev2-xfrmi-06-ipv6
- ping reply didn't flow
- even though GLOBAL=50 ipsec0 has `global`

**Comment by cagney** [comment]
merged

**Pull request closed without merging**
