### PR TITLE
Fixing manpage of pluto.

### PR DESCRIPTION
**Pull request by tanuja3**
Fixed the single inverted commas.
 They were displaying as "doesn*(Aqt" instead of "doesn't".

Signed-off-by: tanuja3 <dtanujakirthi@gmail.com>

### CODE REVIEW

**Comment by letoams** [comment]
Can you show me when or where these are not correctly displayed?
I don't see any issues with the quotes you are fixinf.

**Comment by tanuja3** [comment]
pluto

- At https://libreswan.org/man/ipsec_pluto.8.html the quotes are not being displayed correctly.

**Comment by letoams** [comment]
On Wed, 15 Apr 2020, Tanuja Kirthi Doddapaneni wrote:

> Subject: Re: [libreswan/libreswan] Fixing manpage of pluto. (#314)

> pluto
>
>  *  At https://libreswan.org/man/ipsec_pluto.8.html the quotes are not being displayed correctly.

Ahh, I think that might be a bug in the xmlto package used to convert
the man pages, where in the man pages it shows properly.

I don't think single or double quotes should be replaced everyhwere, eg
see: https://stackoverflow.com/questions/24001878/do-i-need-to-replace-double-single-quote-in-xml-body-text

I'll try and regenerate the html and see if that bug has gone away yet.
It has been a while since we actually updated the html output.

Paul

**Comment by tanuja3** [comment]
Oh okay, then I'll close this pull request. Thank you.

**Pull request closed without merging**
