### PR TITLE
Suppress warnings with GCC 14

### PR DESCRIPTION
**Pull request by ueno**
This fixes the following compiler warning when building on Fedora rawhide (Fedora 41):
```console
  parser.lex: In function ‘glob_include’:
  parser.lex:198:44: error: ‘calloc’ sizes specified with ‘sizeof’ in the earlier argument and not in the later argument [-Werror=calloc-transposed-args]
    198 |         stacktop->fileglob = calloc(sizeof(char *), count + 1);
        |                                            ^~~~
  parser.lex:198:44: note: earlier argument should specify number of elements, later size of each element
  cc1: all warnings being treated as errors
```

### CODE REVIEW

**Comment by cagney** [comment]
backstory https://gcc.gnu.org/pipermail/gcc-patches/2023-December/641030.html

**Comment by ueno** [comment]
> backstory https://gcc.gnu.org/pipermail/gcc-patches/2023-December/641030.html

I see. By the way, this is the only place where bare `calloc` is used. Maybe it could be replaced with `alloc_things`?

**Comment by cagney** [comment]
> I see. By the way, this is the only place where bare `calloc` is used. Maybe it could be replaced with `alloc_things`?

Very Good point.  The corresponding free() call, at least, would also need to be updated.  And a check on where it is used so warrants at least a sniff test.

**Comment by cagney** [comment]
Nice, I'll merge it once the branches are unfrozen.

**Comment by cagney** [comment]
btw, only calloc() in 4.x looks like `calloc(1, size)`.  Anyway testing.

**Comment by cagney** [comment]
19eb4a08e400e05167aed2201222be4b1c18fd3a merged!

**Pull request closed without merging**
