### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by vanillajonathan**

### CODE REVIEW

**Comment by doctaweeks** [comment]
For all the small details:
> The most up to date documentation are
documentation is...

**Comment by letoams** [comment]
thanks. rewritten

**Comment by vanillajonathan** [comment]
I don't think commit 3a15d6f was merged.

**Comment by letoams** [comment]
On Tue, 7 Jun 2016, Jonathan wrote:

> I don't think commit 3a15d6f was merged.

I just merged in some, but not all, changes proposed.

Paul

**Pull request closed without merging**
