### PR TITLE
libswan: add self-tests that exercise IKEv2 key derivation

### PR DESCRIPTION
**Pull request by ueno**
This adds a self-test that exercise key derivation through the
CKM_NSS_IKE_PRF_DERIVE and CKM_NSS_IKE_PRF_PLUS_DERIVE mechanisms
provided by NSS.  As such, while the test vector is taken from CAVP,
it only covers minimal scenarios.

### CODE REVIEW

**Comment by cagney** [comment]
are the algparse* tests passing?

**Comment by ueno** [comment]
> are the algparse* tests passing?

Yes, I confirm both `algparse-01` and `algparse-02-fips` pass with `nsrun --ns`. I was previously checking with `pluto --selftest --debug all` which also passes.

**Comment by cagney** [comment]
Running `./kvm install check testing/pluto/algparse*/` I see:
```
kvmrunner 18.06: final test details:
kvmrunner 18.06:   stats/good/failed/previous=passed: algparse-01 algparse-02-fips
kvmrunner 18.06:   tests/good/errors/LEAK/west: algparse-01 algparse-02-fips
kvmrunner 18.06:   tests/good/errors/output-different/west: algparse-01 algparse-02-fips
kvmrunner 18.06:   tests/good/results/failed: algparse-01 algparse-02-fips
kvmrunner 18.06:   total: algparse-01 algparse-02-fips
kvmrunner 18.06:   total/failed: algparse-01 algparse-02-fips
kvmrunner 18.06: final test results:
kvmrunner 18.06:   stats/good/failed/previous=passed: 2
kvmrunner 18.06:   tests/good/errors/LEAK: 2
kvmrunner 18.06:   tests/good/errors/output-different: 2
kvmrunner 18.06:   tests/good/results/failed: 2
kvmrunner 18.06:   total: 2
kvmrunner 18.06:   total/failed: 2
kvmrunner 18.06: run finished at 2022-06-18 12:25:29.158592 after 0:00:18.663516
```
the difference is that kvmrunner shuts down pluto as part of a postmortem.  Here's the hint:
```
leak: seed_data = Nir || SPIir, item size: 32
leak detective found 1 leaks, total size 32
```

**Comment by ueno** [comment]
@cagney thank you. I still haven't had luck with running `./kvm install`  locally (some permission issues on F36), but pushed a fix that I confirmed with valgrind and `pluto --selftest`.

**Comment by cagney** [comment]
cherry-picked

can you point out on irc where https://libreswan.org/wiki/Test_Suite_-_KVM is failing?
btw for:
```
+       if (!verify_symkey(test->description, prf_output, symkey_output, logger)) {
+               ok = false;
+       }
```
you'll encounter this idiom in the code base:
````
  ok &= ...();
```
either works; the latter because the bool value is the least significant bit of the byte

**Comment by ueno** [comment]
> can you point out on irc where https://libreswan.org/wiki/Test_Suite_-_KVM is failing?

I've posted this on IRC (through Matrix) but in case the bridge doesn't work:

> cagney: the ./kvm install error I am facing at https://github.com/libreswan/libreswan/pull/766#issuecomment-1159636642 is https://paste.centos.org/view/d7af396b

**Comment by cagney** [comment]
Merged.  I liked your solution to fixing the old code.
Also 9e661090be092d13090e8877a7fecb1eb7f50772

**Pull request closed without merging**
