### PR TITLE
Use standard ref counting in pluto kernel xfrmi

### PR DESCRIPTION
**Pull request by bradyallenjohnson**
- Remove locally defined ref counting in kernel_xfrm_interface and replace with libswan/refcnt.c
- Also change unclear bool function returns to use standard c-style returns: 0 - success, non-zero - failure

### CODE REVIEW

**Comment by cagney** [comment]
The refcnt part looks great.

However:
```
-                       if (!setup_xfrm_interface(c, wm->xfrm_if_id == 0 ?
-                                                 PLUTO_XFRMI_REMAP_IF_ID_ZERO : wm->xfrm_if_id )) {
+                       if (setup_xfrm_interface(c, wm->xfrm_if_id == 0 ?
+                                                PLUTO_XFRMI_REMAP_IF_ID_ZERO : wm->xfrm_if_id )) {
                                /* XXX: never happens?!? */
                                return diag("setup xfrmi interface failed");
```
libreswan's code base mostly tries to steer clear of this style.  For instance, string routines use streq() et.al. wrappers.  Exceptions tend to get flagged with:
```
-/* ??? true means failure! */
```

**Comment by cagney** [comment]
FYI, the const cast shouldn't be needed:
```
+                       refcnt_peek((const struct refcnt *) &(c->xfrmi->refcnt)));
```

**Comment by cagney** [comment]
merged by cd6326d638a2cb1bfbfcce33e504452f4a5bb8e6

**Comment by cagney** [comment]
fyi, testing found a leak, https://testing.libreswan.org/?run=v4.9-995-gcd6326d638-main&run=v4.9-990-g99c52cb4c7-main

**Comment by cagney** [comment]
part of the problem is the (forced) use of the global logger, I'll push change so that the connection's logger is passed down

**Comment by cagney** [comment]
I'm wondering about this:
```
@@ -418,7 +418,7 @@ static void process_nlmsgs(char *msgbuf,  ssize_t len, struct ifinfo_response *i
  i++;
  red_msg_size += nlmsg->nlmsg_len;
  dbg("RTM_NEWLINK: netlink %d ignored %d. Bytes %d", i, ignored, red_msg_size);
- if (parse_nl_newlink_msg(nlmsg, ifi_rsp) == 0 && ifi_rsp->result)
+ if (parse_nl_newlink_msg(nlmsg, ifi_rsp) != XFRMI_SUCCESS && ifi_rsp->result)
  return;
  break;
 ```

**Comment by cagney** [comment]
closer https://testing.libreswan.org/v4.9-1016-g9570e97c55-main/ikev2-xfrmi-02/OUTPUT/road.console.diff

**Comment by cagney** [comment]
that fixed the last regression

**Comment by bradyallenjohnson** [comment]
Andrew,

Sorry for not working on this yesterday or today. It's been one of those
weeks and it's only Tuesday...

Thanks for fixing this, I'll look at the details tomorrow.

Regards,

Brady

**Pull request closed without merging**
