### PR TITLE
Updates to dockerfiles & travis build scripts

### PR DESCRIPTION
**Pull request by ericcurtin**
Build, push, pull, list and run dockers. Also, update build script to
use with Travis CI. Enable docker in .travis.yml file also.

### CODE REVIEW

**Comment by ericcurtin** [comment]
Gonna try and get the centos and fedora ones running first, then will continue with the others

**Comment by ericcurtin** [comment]
I might remove centos 6...

/home/curtine/git/libreswan/programs/pluto/ikev2_ipseckey.c:829: undefined reference to `ub_resolve_event'
/home/curtine/git/libreswan/OBJ.linux.x86_64/lib/libswan/libswan.a(unbound.o): In function `unbound_event_init':
/home/curtine/git/libreswan/lib/libswan/unbound.c:182: undefined reference to `ub_ctx_create_event'

I'm gonna assume the latest version of libreswan doesn't build on centos:6 and that only critical stuff is backported. Had installed unbound-devel

**Comment by letoams** [comment]
On Thu, 7 Dec 2017, Eric Curtin wrote:

> I might remove centos 6...
> 
> /home/curtine/git/libreswan/programs/pluto/ikev2_ipseckey.c:829: undefined reference to ub_resolve_event'
> /home/curtine/git/libreswan/OBJ.linux.x86_64/lib/libswan/libswan.a(unbound.o): In functionunbound_event_init':
> /home/curtine/git/libreswan/lib/libswan/unbound.c:182: undefined reference to `ub_ctx_create_event'
> 
> I'm gonna assume the latest version of libreswan doesn't build on centos:6 and that only critical stuff is backported. Had installed
> unbound-devel

Yes, libunbound was compiled without libevent support. It is not
scheduled to be fixed for RHEL6.

Is there any reason the docketfiles are in the root dir and not in
something like the testing/docketfiles subdirectory ?

Paul

**Comment by ericcurtin** [comment]
I can move them into testing/dockerfiles, no biggie

**Comment by ericcurtin** [comment]
ikev2_ipseckey.o: In function `dns_qry_start':
/home/curtine/git/libreswan/programs/pluto/ikev2_ipseckey.c:829: undefined reference to `ub_resolve_event'
/home/curtine/git/libreswan/OBJ.linux.x86_64/lib/libswan/libswan.a(unbound.o): In function `unbound_event_init':
/home/curtine/git/libreswan/lib/libswan/unbound.c:182: undefined reference to `ub_ctx_create_event'

and RHEL 7 too I guess, maybe just fedora then

**Comment by letoams** [comment]
On Thu, 7 Dec 2017, Eric Curtin wrote:

> ikev2_ipseckey.o: In function dns_qry_start': /home/curtine/git/libreswan/programs/pluto/ikev2_ipseckey.c:829: undefined reference
> toub_resolve_event'
> /home/curtine/git/libreswan/OBJ.linux.x86_64/lib/libswan/libswan.a(unbound.o): In function unbound_event_init':
> /home/curtine/git/libreswan/lib/libswan/unbound.c:182: undefined reference toub_ctx_create_event'
> 
> and RHEL 7 too I guess, maybe just fedora then

rhel-7.5 will get updated libunbound. you can drag in these from our own
libreswan binary repository for rhel7 at download.libreswan.org/binaries/rhel/7/

Paul

**Comment by ericcurtin** [comment]
Yeah I'll build on fedora 25-27 for now... Will drag in centos 7.5 when it gets released... It will be much easier that way... If that's ok?

**Comment by ericcurtin** [comment]
Just want to get this build going... And then drag in other platforms

**Comment by ericcurtin** [comment]
Removing clang also... I added clang along with gcc, because every project I compile against clang... The compilers warnings find issues... Maybe can add after... Just gonna go gcc for now

**Comment by ericcurtin** [comment]
Ok this is good for review @letoams 

Last step after this is merged is to remove references to curtine dockerhub account.

from

testing/dockerfiles/docker.sh
scripts/build.sh

Add sign up for generic "libreswan" Travis CI and dockerhub (set up an automated docker image build here to make life easy) accounts. Any questions just ask! You can set up free, nightly, master, pull request builds, etc. then.

And add labels and the like to README.md

Or we can keep them on my accounts. I'm not sure if that's a good thing though, because then only I have access!

**Comment by ericcurtin** [comment]
I was able to create https://hub.docker.com/r/libreswan/ organisation, won't be able to hook up any of this to libreswan on GitHub (Travis CI or dockerhub), unless I become member of the organisation on GitHub :smile:

**Comment by letoams** [comment]
On Fri, 8 Dec 2017, Eric Curtin wrote:

> I was able to create https://hub.docker.com/r/libreswan/ organisation, won't be able to hook up any of this to
> libreswan on GitHub (Travis CI or dockerhub), unless I become member of the organisation on GitHub ?

Our repository there is an export-only push. We don't pull in changes
via github. What access do you need after I pulled in and applied your
PR?

Paul

**Comment by ericcurtin** [comment]
It will build every-time a commit is made to master and release-3.23 branches (regardless if this is via Github or another way). And on every GitHub Pull Request that is open. And you can also schedule nightly builds, to be extra safe, probably getting a bit pedantic at that stage as it will build every-time a commit is made to master and release-3.23 branches anyway. But the build servers are free, so why not I guess?

Even if you don't pull in the changes via GitHub, it it will still automatically run a build when a GitHub pull request is opened so you can check did it pass before you pull in changes using whatever technique you use: git CLI, etc.

You need to add me to the libreswan github organisation to hook in the builds, or someone who is already a member could do it. It's a github configuration:

https://help.github.com/articles/adding-organization-members-to-a-team/
https://help.github.com/articles/inviting-users-to-join-your-organization/

I don't know for sure if you can add me and just give me only read access to the repo or just read/write access.

**Comment by libreswan** [comment]
the libreswan account is not an "organiation", so I think the only way we could do this is for this account to put the hooks in? Alternatively, we could change this account into an organisation but that will screw up all existing ssh keys and commit access

**Comment by ericcurtin** [comment]
Didn't know it was a user account...

https://help.github.com/articles/converting-a-user-into-an-organization/

We could attempt to use the same ssh key pairs in the organisation? Maybe it's not worth the risk...
Adding me as a collaborator in the "libreswan" project settings might work too...

Or someone who already has access to the libreswan account could do it?

I really don't mind... :smile:

**Comment by letoams** [comment]
On Fri, 8 Dec 2017, Eric Curtin wrote:

> Or someone who already has access to the libreswan account could do it?

That seems the easiest, if you can describe what needs to be done?

**Comment by ericcurtin** [comment]
Set up account on https://travis-ci.org/, link to github account, configure the builds. It's really ituitive, shouldn't be tricky, but if you get stuck feel free to send me a message.

Similarly set up an account on dockerhub, send your username, I can add you to this organization:

https://hub.docker.com/u/libreswan

Then you will have to create automated builds for the images. Again it's not too bad pretty intuitive. Send a message if you get stuck!

**Comment by letoams** [comment]
antony has merged in slightly different scripts

**Pull request closed without merging**
