### PR TITLE
libswan: use ikev2_prf wrapper functions in KDF self-tests

### PR DESCRIPTION
**Pull request by ueno**
This fixes a build issue on the systems with old NSS, by removing the assumption that the KDF is always backed by NSS.

This should fix the build issue on Debian, as mentioned at https://github.com/libreswan/libreswan/pull/766#issuecomment-1177781437

### CODE REVIEW

**Comment by ueno** [comment]
@cagney I've pushed the commit reflecting your suggestion at https://github.com/ueno/libreswan/commit/62d37bbbc2e795e46fcab0be7e13124e87ec7465

**Comment by cagney** [comment]
Did you try building and running algparse with USE_NSS_KDF = false?

**Comment by ueno** [comment]
> Did you try building and running algparse with USE_NSS_KDF = false?

Thanks, I've fixed it. Could you take a look again?

**Comment by ueno** [comment]
Closing as the change has been merged as part of #766.

**Pull request closed without merging**
